---
- name: "install expenses-app demo application"
  hosts: "localhost"
  gather_facts: false
  connection: local
  become: false
  vars:
      # default will be $HOME/.kube/config
      kubeconfig: "{{ lookup('env','KUBECONFIG')}}"
  vars_files:
      - vars/vars.yaml
  roles:
      - {role: openshift-pipeline-operator}
      - {role: sso-operator}
      - {role: expenses-app-pipelines}
