---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-image
spec:
  params:
    - name: VERSION
      description: "The version of the build image"
      default: '20.1.0-java11'
      type: string
    - name: PATH_CONTEXT
      description: "The location of the path to run s2i from."
      default: .
      type: string
    - name: TLSVERIFY
      description: "Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)"
      default: "false"
      type: string
    - name: STORAGE_DRIVER
      description: Set buildah storage driver
      type: string
      default: vfs

  
  resources:
    outputs:
      - name: image
        type: image
  steps:
    - name: build
      image: quay.io/buildah/stable
      workingdir: /workspace/source
      script: |
        #!/usr/bin/env bash

        echo "working dir:  $PWD"
        cat src/main/docker/Dockerfile.native

        echo
        buildah version
        echo
        echo
        echo "run buildah "
        echo " output image:  $(outputs.resources.image.url)"
        echo
        buildah --storage-driver=$(inputs.params.STORAGE_DRIVER) bud  --tls-verify=$(inputs.params.TLSVERIFY) \
          --layers -f src/main/docker/Dockerfile.native -t  $(outputs.resources.image.url) .

      
        echo
        echo
        echo
        echo "push image"
        buildah --storage-driver=$(inputs.params.STORAGE_DRIVER) push --tls-verify=$(inputs.params.TLSVERIFY) \
          $(outputs.resources.image.url) docker://$(outputs.resources.image.url)


      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
        - name: gen-source
          mountPath: /gen-source
        - name: devfuse
          mountPath: /dev/fuse
    # securityContext:
    #   privileged: true

  volumes:
    - name: varlibcontainers
      emptyDir: {}
    - name: gen-source
      emptyDir: { }
    - name: devfuse
      emptyDir: { }
  workspaces:
    - name: input
      mountPath: /workspace/source
