---
#  tasks for openshift4
# ------------------------------------------------------------------------------
# Configure backend
# ------------------------------------------------------------------------------



- name: "Set KUBECONFIG contents if not defined"
  set_fact:
    kubeconfig: "{{ lookup('env','HOME') + '/.kube/config' }}"
  when: kubeconfig == "" or kubconfig is undefined


- debug:
    var=kubeconfig


- name: Gather installed openshift_cli  version, if there is any
  ansible.builtin.shell:
    cmd: |
      {{openshift_cli }} version | head -1
  register: ocresult
  check_mode: false
  changed_when: false
  failed_when: (ocresult.rc != 0) or ( ocresult.stderr != "")
  tags:
    - backend
    - web
    - full-app-deploy

- debug:
      msg: " {{openshift_cli }} version: {{ ocresult.stdout }}"
  tags:
    - backend
    - full-app-deploy
    - web


- name: Create Namespace for application
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    definition:
      kind: Namespace
      apiVersion: v1
      metadata:
        name: "{{ app_namespace }}"
  tags:
    - backend
    - full-app-deploy
    - web

- name: "deploy buildah tekton pipline tasks"
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ app_namespace }}"
    src: "{{ item }}"
  loop:
    - common/tekton-task/buildah.yaml
  tags:
    - backend
    - full-app-deploy
    - web

- name: "add admin to pipline service account"
  ansible.builtin.shell: |
    {{ openshift_cli }} policy add-role-to-user \
       admin system:serviceaccount:{{ app_namespace}}:pipeline \
      -n {{ app_namespace}}

    echo
    echo "add scc to sa pipeline"
    {{ openshift_cli }} adm policy add-scc-to-user  privileged -z pipeline -n {{ app_namespace}}

    exit 0
  changed_when: false
  tags:
    - backend
    - full-app-deploy
    - web




- name: "get full sso url from route"
  ansible.builtin.shell: |
    {{ openshift_cli }} get route -n {{ sso_operator_namespace }} \
    keycloak -o jsonpath=\{.spec.host\}
    exit 0
  register: ssohost
  tags:
    - backend
    - full-app-deploy
    - web



- import_tasks: backend.yaml
  tags:
    - backend
    - full-app-deploy


- import_tasks: webapp.yaml
  tags:
    - web
    - full-app-deploy
