---
#  tasks for openshift4
# ------------------------------------------------------------------------------
# Configure sso
# ------------------------------------------------------------------------------



- name: "Set KUBECONFIG contents if not defined"
  set_fact:
    kubeconfig: "{{ lookup('env','HOME') + '/.kube/config' }}"
  when: kubeconfig == "" or kubconfig is undefined


- debug:
      var=kubeconfig



- name: Gather installed openshift_cli  version, if there is any
  ansible.builtin.shell:
    cmd: |
      {{openshift_cli }} version | head -1
  register: ocresult
  check_mode: false
  changed_when: false
  failed_when: (ocresult.rc != 0) or ( ocresult.stderr != "")


- debug:
      msg: " {{openshift_cli }} version: {{ ocresult.stdout }}"


- import_tasks: sso-operator.yaml
  tags:
    - sso
