---
#  tasks for openshift4
# ------------------------------------------------------------------------------
# Configure sso
# ------------------------------------------------------------------------------



- name: "Set KUBECONFIG contents if not defined"
  set_fact:
    kubeconfig: "{{ lookup('env','HOME') + '/.kube/config' }}"
  when: kubeconfig == "" or kubconfig is undefined


- debug:
      var=kubeconfig



- name: Gather installed openshift_cli  version, if there is any
  ansible.builtin.shell:
    cmd: |
      {{openshift_cli }} version | head -1
  register: ocresult
  check_mode: false
  changed_when: false
  failed_when: (ocresult.rc != 0) or ( ocresult.stderr != "")



- debug:
      msg: " {{openshift_cli }} version: {{ ocresult.stdout }}"



- name: "sso: check wildcard domain for tls_route"
  ansible.builtin.debug:
    msg:
      - "wildcard domain is set {{ wildcard_domain is defined }} "
      - "tls_route is defined: {{ tls_route is defined }}"
  failed_when:
    - wildcard_domain is not defined
    - tls_route is defined
  tags:
    - sso


- name: "sso: check if operator already installed"
  ansible.builtin.shell: |
    {{ openshift_cli }} get pods -l name=rhsso-operator   -n {{ sso_operator_namespace }} --ignore-not-found \
    | wc -l
    exit 0
  register: ssopodsrunning
  tags:
    - sso


- import_tasks: sso-operator.yaml
  when: "'0' in ssopodsrunning.stdout"
  tags:
    - sso
