apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: test-nodejs-app
spec:
  params:
    - name: BUILD_IMAGE
      description: The version of the nodejs
      default: "registry.redhat.io/rhscl/nodejs-14-rhel7:1-91"
      type: string
  steps:
      - name: test-app
        image: "$(inputs.params.BUILD_IMAGE)"
        workingDir: /workspace/input-ui-source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            echo "test project"
            pwd
            ls
            echo "current git branch: $(git rev-parse --abbrev-ref HEAD)"

            echo "install yarn first"
            npm install -g yarn
            yarn --version
            echo "install dependencies"
            yarn


            echo "run tests"
            yarn test
  workspaces:
    - name: input
      mountPath: /workspace/input-ui-source
