apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: backend-build-run-oidc-branch
spec:
  params:
    - name: git-revision
      value: "oidc"
    - name: keycloak_url
      value: "http://sso-test-nm-demo.apps.ocp-cluster-1.rhlab.ch"

  pipelineRef:
    name: build-and-deploy-backend
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: source-pvc
  resources:
    - name: backend-image
      resourceRef:
        name: backend-image
