apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: backend-build-run-v2-tag
spec:
  params:
    - name: git-revision
      value: "v2.0.0"
    - name: keycloak_url
      value: "http://sso-test-nm-demo.apps.apps-crc.testing"
  pipelineRef:
    name: build-and-deploy-backend
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: source-pvc
  resources:
    - name: backend-image
      resourceRef:
        name: backend-image
