---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: backend-run-feature-kafka-branch
spec:
  params:
    - name: git-revision
      value: "feature/kafka"
    - name: keycloak_url
      value: "http://sso-test-nm-demo.apps.ocp001.rhlab.ch"
  pipelineRef:
    name: build-and-deploy-backend
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: source-pvc
  resources:
    - name: backend-image
      resourceRef:
        name: backend-image
