apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: backend-run-
spec:
  params:
    - name: git-revision
      value: "pg-fix"
    - name: keycloak_url
      value: "http://sso-test-expenses.apps.ocp5.stormshift.coe.muc.redhat.com"
    - name: sso-service-name
      value: sso-test

  pipelineRef:
    name: build-and-deploy-backend
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: source-pvc
  resources:
    - name: backend-image
      resourceRef:
        name: backend-image
