---
# test mvn test command
apiVersion: tekton.dev/v1beta1
kind: TaskRun

metadata:
  generateName: mvn-test-taskrun

spec:
  taskRef:
    name: backend-mvn
  params:
    - name: GOALS
      value: "clean test"
    - name: keycloak_url
      value: "https://keycloak-nm-sso.apps-crc.testing"
  workspaces:
    - name: input
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

      #persistentVolumeClaim:
      #  claimName: source-pvc
